### ISSUE TITLE
Invalid VCL assigning time

### ISSUE THREAD

**Issue by ejthurgo** [queueit/KnownUser.Fastly#4]
There is an issue with the VCL:
https://github.com/queueit/KnownUser.Fastly/blob/72f15daed6a1b1f43b7da2cd625b2a0a90fab932/Queue-it%20Connector.vcl#L213-L214

Gives the following error when deploying to a service.

```
Assignment not possible between type `TIME` and type `TIME`
at: (input Line 453 Pos 60)
  set var.exptime += std.time(var.cookie_validitytime, 20m);
-----------------------------------------------------------#

Syntax error: Expected an action, `if`, `{` or `}`
at: (input Line 386 Pos 5)
sub validate_queueit_token {
----######################--
```

Instead of using the addition assignment operator `+=`. Use `time.add` ([docs](https://www.fastly.com/documentation/reference/vcl/functions/date-and-time/time-add/))

```
set var.exptime = time.add(now, std.time(var.cookie_validitytime, 20m));
```

**Comment by 3520kramer** [comment]
Thanks for making us aware of this issue @ejthurgo
